### ISSUE TITLE
v.2.0.1 is treating the tomtom waypoints and arrows, as an icon

### ISSUE THREAD

**Issue by karpana** [Ketrel/MinimapButtonFrame-Redux#4] opened 2022-10-31 14:54 UTC
I just did the manual install of v2.0.1, and things are looking solid.
I even got back my "square tokens" that I was using prior to the "fanfix hack" I did.
Thank you!!!

One observation about the latest update, there's a weird incompatibility with TomTom.
the TomTom arrow and waypoints which are normally shown in the minimap, are getting picked up by MBF-R.

In the minimap, they look to have squares on them, and when MBF-R can snag the icons, they'll show up as "buttons" in the MBF-R frame.

(I'll post screen caps in the next comment)

**Comment by karpana** [comment] 2022-10-31 14:56
![image](https://user-images.githubusercontent.com/15716173/199038641-0b98de9d-2305-433d-91b5-4a7f7767dbc3.png)

**Comment by Ketrel** [comment] 2022-10-31 17:26
That's odd, let me see if I can reproduce that.  Even if I can't, I should be able to add them to the hardcoded blacklist.

**Comment by Ketrel** [comment] 2022-10-31 18:38
This is fixed in 2.0.2.
This can actually be handled in settings by adding the button to "Protected Items" in settings under exceptions.  
In this case, you would've have needed to add "TTMinimapButton" to that and then reloaded.  
Since TomTom is a widely used addon, I added it to the hardcoded ones.

**Closed as completed by Ketrel** 2022-10-31 18:38 UTC
